on:
  pull_request:

name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
    - run: go test -coverprofile coverage.out -v ./uptycs/...
